// Seed data for Client Health Agent — edit account/lead/cash data here.
// Loaded as a classic <script> in the DC <helmet>, so these globals exist
// before the component initializes its state.
window.CHA_DATA = {
    active:'today', expanded:null, newTask:'', tab:'all', toast:null, modal:null, modalBody:'',
    esc:null,
    signedIn:false, loginEmail:'', loginPw:'',
    openAccount:null, drawerTab:'signals', markOk:false, logNote:'',
    senderEmail:'', emailDraft:'', openLeadId:null, blockerDraft:'', solutionDraft:'',
    leadBlockers:{
      l1:[{blocker:'Comparing us against their incumbent vendor',solution:'Side-by-side ROI + faster fill times shorten their time-to-value'}],
      l2:[{blocker:'Needs sign-off from the ops lead',solution:'Exec one-pager + a 14-day pilot to prove it before they commit'}],
      l3:[{blocker:'Finance approval required before signing',solution:'Flexible monthly terms + a clear cost-per-fill breakdown'}],
      l4:[{blocker:'Low urgency — need is not yet felt',solution:'Peer case study showing the real cost of unfilled roles'}],
    },
    addCust:false, custFromLead:null, custForm:{company:'',vertical:'',contact:'',email:'',phone:'',arr:'',segment:'Mid-Market',csm:'Brandy',renewal:'',term:'12-mo',startDate:'',billing:'Monthly',contractNum:'',docName:'',address:'',sponsor:'',sponsorEmail:''},
    addLead:false, newLead:{company:'',type:'Healthcare',segment:'Mid-Market',region:'West',contact:'',title:'',email:'',phone:'',linkedin:'',source:'Inbound form',interest:'Warm',size:'',value:'',timeline:'30–60 days',note:''},
    pipeView:'board', onbChecks:{},
    implExpanded:null, msDraftName:'', msDraftDate:'', implNoteDraft:'',
    implMilestones:{ l6:[{name:'Kickoff call',date:'Jun 24',done:true},{name:'Access provisioned',date:'Jun 28',done:false},{name:'First invoice sent',date:'Jul 1',done:false},{name:'Go-live',date:'Jul 15',done:false}] },
    implNotes:{ l6:[{body:'COO wants weekly check-ins through launch. First 5 reqs already shared.',who:'Renata',when:'Jun 19'}] },
    leadForm:{type:'Follow-up',note:'',outcome:'Awaiting reply',snooze:'6mo'},
    leadSnooze:{l4:'Dec 2026'},
    leadTouches:{
      l1:[{type:'Initial outreach',date:'May 28',note:'Intro email after their inbound form. Asked for pricing on a 20-seat plan.',outcome:'Awaiting reply',by:'Theo'}],
      l2:[{type:'Initial outreach',date:'May 30',note:'Referral intro from a mutual contact; sent a one-pager overview.',outcome:'Replied',by:'Brandy'},{type:'Follow-up',date:'Jun 2',note:'Sent the proposal — opened it 3 times since.',outcome:'Awaiting reply',by:'Brandy'}],
      l3:[{type:'Call',date:'Jun 6',note:'Ran a full demo; reception was positive. Needs finance sign-off before moving.',outcome:'Awaiting reply',by:'Renata'}],
      l4:[{type:'Initial outreach',date:'Jun 14',note:'Cold intro; got a single reply then went quiet.',outcome:'Not a good time',by:'Brandy',nextFollowUp:'Dec 2026'}],
    },
    leads:[
      {id:'l1',company:'Brookline Pediatrics',stage:'contacted',reachedOut:'Jun 9',nextFollowUp:'Jun 20',attempt:2,maxAttempts:4,type:'Healthcare',segment:'Mid-Market',region:'West',contact:'Janet Pyle',title:'Ops Director',email:'janet@meridiancare.com',phone:'(415) 555-0182',linkedin:'linkedin.com/in/janetpyle',reachedOutBy:'Theo',lastTouch:'9 days ago',interest:'Warm',value:'60',timeline:'30–60 days',source:'Inbound form',sub:'No reply in 9 days · warm lead',
        fit:[true,true,true,false,true,true,false,false],
        notes:[{body:'Asked for pricing on a 20-seat plan. Wants to compare against their incumbent.',who:'Theo',when:'May 28'}],
        tasks:[{id:'lt1',label:'Send 20-seat pricing breakdown',done:false},{id:'lt2',label:'Share home-health case study',done:true}]},
      {id:'l2',company:'Lumen Events Co',stage:'engaged',reachedOut:'Jun 2',nextFollowUp:'—',attempt:3,maxAttempts:4,type:'Hospitality',segment:'SMB',region:'Midwest',contact:'Dele Akin',title:'Founder',email:'dele@foxgloveevents.com',phone:'(312) 555-0147',linkedin:'linkedin.com/in/deleakin',reachedOutBy:'Brandy',lastTouch:'7 days ago',interest:'Hot',value:'48',timeline:'< 30 days',source:'Referral',sub:'No reply in 7 days · opened email 3x',
        fit:[true,true,true,true,false,true,false,true],
        notes:[{body:'Opened the proposal 3 times — high intent. Budget confirmed verbally.',who:'Brandy',when:'Jun 2'}],
        tasks:[{id:'lt1',label:'Nudge on the open proposal',done:false}]},
      {id:'l3',company:'Granite Peak Gear',stage:'qualified',reachedOut:'Jun 6',nextFollowUp:'—',attempt:2,maxAttempts:4,type:'Retail',segment:'Mid-Market',region:'West',contact:'Sam Ortega',title:'VP People',email:'sam@trailheadco.com',phone:'(503) 555-0119',linkedin:'linkedin.com/in/samortega',reachedOutBy:'Renata',lastTouch:'4 days ago',interest:'Warm',value:'85',timeline:'60–90 days',source:'Demo request',sub:'Demo done · awaiting proposal',
        fit:[false,true,true,true,false,false,true,false],
        notes:[{body:'Demo went well; needs sign-off from finance. Timeline ~30 days.',who:'Renata',when:'Jun 6'}],
        tasks:[{id:'lt1',label:'Send proposal v1',done:false},{id:'lt2',label:'Loop in their finance lead',done:false}]},
      {id:'l4',company:'Tidewater Talent',stage:'prospect',reachedOut:'—',nextFollowUp:'Jun 22',attempt:0,maxAttempts:4,type:'Staffing',segment:'SMB',region:'Northeast',contact:'Nadia Hassan',title:'Owner',email:'nadia@birchco.com',phone:'(206) 555-0173',linkedin:'linkedin.com/in/nadiahassan',reachedOutBy:'Brandy',lastTouch:'2 days ago',interest:'Cold',value:'30',timeline:'90+ days',source:'Cold outreach',sub:'No reply since intro · cold',
        fit:[false,false,true,false,true,false,true,false],
        notes:[{body:'Single cold reply, then quiet. Low urgency for now.',who:'Brandy',when:'Jun 14'}],
        tasks:[{id:'lt1',label:'Try one more value-led touch',done:false}]},
      {id:'l5',company:'Maplewood Senior Care',stage:'proposal',reachedOut:'May 28',nextFollowUp:'—',attempt:3,maxAttempts:4,type:'Healthcare',segment:'Mid-Market',region:'West',contact:'Lena Park',title:'Administrator',email:'lena@cedarridge.com',phone:'(408) 555-0190',linkedin:'linkedin.com/in/lenapark',reachedOutBy:'Brandy',lastTouch:'3 days ago',interest:'Hot',value:'95',timeline:'< 30 days',source:'Referral',sub:'Proposal sent · reviewing',
        fit:[true,true,true,true,true,true,true,false],
        notes:[{body:'Proposal sent for 30 beds of coverage. Verbal yes pending board approval.',who:'Brandy',when:'Jun 16'}],
        tasks:[{id:'lt1',label:'Confirm board approval date',done:false}]},
      {id:'l6',company:'Ironside Logistics',stage:'signed',reachedOut:'May 12',nextFollowUp:'—',attempt:2,maxAttempts:4,type:'Staffing',segment:'Enterprise',region:'Midwest',contact:'Ray N.',title:'COO',email:'ray@pinnacle.com',phone:'(312) 555-0144',linkedin:'linkedin.com/in/raynguyen',reachedOutBy:'Renata',lastTouch:'1 day ago',interest:'Hot',value:'140',timeline:'signed',source:'Outbound',sub:'Signed · starting onboarding',
        fit:[true,true,true,true,true,true,true,true],
        notes:[{body:'Contract signed. Kickoff scheduled — move to onboarding checklist.',who:'Renata',when:'Jun 18'}],
        tasks:[{id:'lt1',label:'Schedule onboarding kickoff',done:false}]},
      {id:'l7',company:'Brightwater Health',stage:'signed',reachedOut:'May 20',nextFollowUp:'—',attempt:2,maxAttempts:4,type:'Healthcare',segment:'Mid-Market',region:'West',contact:'Dana Portis',title:'VP Ops',email:'dana@brightwater.com',phone:'(206) 555-0171',linkedin:'—',reachedOutBy:'Margo',lastTouch:'2 days ago',interest:'Hot',value:'95',timeline:'signed',source:'Referral',sub:'Signed · onboarding',
        signedInfo:{csm:'Margo Quinn',startDate:'Jul 8, 2026',value:95,valueType:'one-time',roles:'8',term:'12-mo'},
        fit:[true,true,true,true,true,true,true,false],
        notes:[{body:'Signed for 8 beds of coverage. Kickoff set for early July.',who:'Margo',when:'Jun 19'}],
        tasks:[{id:'lt1',label:'Send onboarding packet',done:false}]},
      {id:'l8',company:'Cobalt Manufacturing',stage:'signed',reachedOut:'May 28',nextFollowUp:'—',attempt:3,maxAttempts:4,type:'Light industrial',segment:'Enterprise',region:'Midwest',contact:'Marcus To',title:'Plant Director',email:'marcus@cobalt.com',phone:'(414) 555-0188',linkedin:'—',reachedOutBy:'Theo',lastTouch:'4 days ago',interest:'Hot',value:'120',timeline:'signed',source:'Outbound',sub:'Signed · onboarding',
        signedInfo:{csm:'Theo Banks',startDate:'Jul 15, 2026',value:120,valueType:'one-time',roles:'14',term:'12-mo'},
        fit:[true,true,true,true,true,true,false,true],
        notes:[{body:'Signed for 2nd-shift staffing. Coordinating start with their HR.',who:'Theo',when:'Jun 17'}],
        tasks:[{id:'lt1',label:'Confirm shift schedule with HR',done:false}]},
    ],
    history:[
      {id:'h1',text:'Approved & sent renewal touch to Summit Facilities',kind:'send',who:'You',time:'2d ago'},
      {id:'h2',text:'Logged outreach for Harbor Point Clinics',kind:'outreach',who:'You',time:'2d ago'},
      {id:'h3',text:'Snoozed Riverside Dental Group for 3 days',kind:'snooze',who:'You',time:'3d ago'},
      {id:'h4',text:'Synced 12 new placements from Google Sheet',kind:'sync',who:'Agent',time:'3d ago'},
    ],
    items:[
      {id:'a1',company:'Northwind Logistics',vertical:'Warehousing',initials:'NL',arr:148000,score:41,prev:59,status:'pending',contact:'Dana Whitfield',playKind:'re-engagement email',subject:'Checking in on your open Northwind reqs',
        signals:['Zero placements filled in 24 days — your longest gap with them','Dana opened 3 reqs but stopped replying on Apr 2','Satisfaction pulse slipped from 8 to 4'],
        body:"Hi Dana,\n\nA few of your open roles have been sitting for a couple weeks and I wanted to get ahead of it. We've got three pre-vetted candidates who fit the warehouse leads you posted — happy to send profiles today.\n\nWould 15 minutes this week help us get these filled?\n\nBest,\nBrandy Mangum"},
      {id:'a2',company:'Cedar & Vine Hospitality',vertical:'Hospitality',initials:'CV',arr:96000,score:38,prev:51,status:'pending',contact:'Marco Ruiz',playKind:'payment nudge',subject:'Quick note on invoice #2471',
        signals:['Invoice #2471 is 38 days overdue ($7,400)','Seasonal ramp usually starts by now — no reqs opened','Two roles posted in March, none filled'],
        body:"Hi Marco,\n\nJust flagging invoice #2471 in case it slipped through — no rush, I just want to keep things clean on our end.\n\nSummer hiring usually kicks off around now too; I can have a shortlist of servers and line staff ready this week whenever you are.\n\nTalk soon,\nBrandy Mangum"},
      {id:'a3',company:'Brightpath Home Health',vertical:'Healthcare',initials:'BH',arr:210000,score:52,prev:64,status:'pending',contact:'Priya Anand',playKind:'renewal touch',subject:'Quick Brightpath check-in before renewal',
        signals:['Fill rate dropped to 62% over the last 30 days','Contract renews in 41 days — your largest account','Champion Priya moved roles last month'],
        body:"Hi Priya,\n\nCongrats on the new role — I'd love to reconnect and make sure our coverage still lines up with where the team is headed. Your renewal is about six weeks out, so it's a good moment to review what's working.\n\nDo you have 20 minutes next week?\n\nWarmly,\nBrandy Mangum"},
      {id:'a4',company:'Apex Precision Mfg',vertical:'Manufacturing',initials:'AP',arr:124000,score:58,prev:67,status:'pending',contact:'Glen Tomas',playKind:'coverage nudge',subject:'Covering this week’s open shifts at Apex',
        signals:['Two shifts went unfilled this week','Timesheet approvals running 4+ days behind'],
        body:"Hi Glen,\n\nWe had two shifts come up uncovered this week and I don't want that to become a pattern. I've lined up floaters who've worked your floor before and can step in immediately.\n\nWant me to schedule them for the rest of the week?\n\nThanks,\nBrandy Mangum"},
      {id:'a5',company:'Riverside Dental Group',vertical:'Healthcare',initials:'RD',arr:44000,score:63,prev:70,status:'pending',contact:'Sara Lin',playKind:'check-in email',subject:'Anything we can help staff at Riverside?',
        signals:['Usage down ~30% month over month','No new reqs in 18 days'],
        body:"Hi Sara,\n\nThings have been quieter on the scheduling side and I wanted to check in — are you fully covered right now, or is there anything coming up we can get ahead of?\n\nAlways here,\nBrandy Mangum"},
      {id:'a6',company:'Lakeside Retail Co',vertical:'Retail',initials:'LR',arr:72000,score:78,prev:74,status:'clear',contact:'Owen Pratt',signals:['Fill rate steady at 94%','Reqs up 12% this quarter']},
      {id:'a7',company:'Summit Facilities',vertical:'Facilities',initials:'SF',arr:135000,score:71,prev:69,status:'clear',contact:'Renee Cho',signals:['Renewed early last month','Consistent weekly orders']},
      {id:'a8',company:'Harbor Point Clinics',vertical:'Healthcare',initials:'HP',arr:190000,score:85,prev:83,status:'clear',contact:'Dr. Aimee Vance',signals:['Highest satisfaction score in portfolio','Expanding to a 3rd location']},
    ],
    tasks:[
      {id:'t1',label:'Call Dana at Northwind about the dormant reqs',meta:'Due today',done:false},
      {id:'t2',label:'Send Q3 business review deck to Brightpath',meta:'Tomorrow',done:false},
      {id:'t3',label:'Confirm Cedar & Vine seasonal ramp dates',meta:'Done · 2d ago',done:true},
      {id:'t4',label:'Start Brightpath renewal — 41 days out',meta:'This week',done:false},
    ],
    worklist:{
      daily:[{id:'d1',label:'Renewal check-in — Brightpath renews in 41d',auto:true,done:false},{id:'d2',label:'Call Dana at Northwind about dormant reqs',auto:false,done:false},{id:'d3',label:'Reach out to Cedar & Vine — invoice 38d overdue',auto:true,done:false},{id:'d4',label:'Re-engage Riverside Dental — usage down 30%',auto:false,done:false}],
      weekly:[{id:'w1',label:'Schedule QBR — Apex Precision (this week)',auto:true,done:false},{id:'w2',label:'Send proposal to Trailhead Outfitters',auto:false,done:false},{id:'w3',label:'Review at-risk accounts and re-rank',auto:true,done:false}],
      monthly:[{id:'m1',label:'Pull health + ARR trends for the full book',auto:true,done:false},{id:'m2',label:'Sync with finance on expansion signals',auto:false,done:false}],
      quarterly:[{id:'q1',label:'Schedule QBR — Harbor Point renews Sep',auto:true,done:false},{id:'q2',label:'Book concentration / key-person review',auto:true,done:false}],
    },
    teamNotes:[
      {id:'tn1',body:'Confirmed the two core triggers; thresholds set at 30% MoM, validating against real data.',when:'Jun 18, 5:04 PM'},
    ],
    newNote:'',
    worklistDrafts:{daily:'',weekly:'',monthly:'',quarterly:''},
    calEvents:{12:{label:'Brightpath renews',acct:'a3',kind:'renewal'},24:{label:'Apex renews',acct:'a4',kind:'renewal'},9:{label:'Pricing follow-up',kind:'task'},16:{label:'QBR prep',kind:'task'}},
    calSel:null,
    cashStart:78400,
    goalQ:280, goalY:1050,
    cashTab:'log',
    fcSel:null,
    cashRange:'mtd',
    openTxId:null, txNoteDraft:'',
    txEdit:false, txEditForm:{}, txAudit:{},
    txNotes:{ c1:[{body:'Paid in full — invoice #2480 cleared.',when:'Jun 18'}], c2:[{body:'Bi-weekly run for 14 staff. Hours verified against timesheets.',when:'Jun 17'}] },
    txForm:{dir:'out',party:'',amount:'',category:'Payroll',catCustom:false,method:'ACH',check:'',memo:'',client:''},
    cashTx:[
      {id:'c1',date:'Jun 18',dir:'in',party:'Brightpath Home Health',category:'Client payment',method:'ACH',check:'',amount:17500,memo:'Invoice #2480'},
      {id:'c2',date:'Jun 17',dir:'out',party:'Payroll run — 14 staff',category:'Payroll',method:'ACH',check:'',amount:28600,memo:'Bi-weekly'},
      {id:'c3',date:'Jun 15',dir:'out',party:'Northbay Office LLC',category:'Rent',method:'Check',check:'1042',amount:4200,memo:'June rent'},
      {id:'c4',date:'Jun 14',dir:'in',party:'Apex Precision Mfg',category:'Client payment',method:'ACH',check:'',amount:12400,memo:'Invoice #2476'},
      {id:'c5',date:'Jun 12',dir:'out',party:'QuickBooks + software',category:'Software',method:'Card',check:'',amount:740,memo:'Monthly SaaS'},
      {id:'c6',date:'Jun 11',dir:'out',party:'State tax deposit',category:'Taxes',method:'ACH',check:'',amount:6300,memo:'Q2 estimate'},
      {id:'c7',date:'Jun 10',dir:'in',party:'Harbor Point Clinics',category:'Client payment',method:'ACH',check:'',amount:19000,memo:'Invoice #2470'},
      {id:'c8',date:'Jun 7',dir:'out',party:'Payroll run — 14 staff',category:'Payroll',method:'ACH',check:'',amount:28100,memo:'Bi-weekly'},
      {id:'c9',date:'Jun 6',dir:'out',party:'Indeed + LinkedIn ads',category:'Marketing',method:'Card',check:'',amount:1850,memo:'Job posts'},
      {id:'c10',date:'Jun 4',dir:'in',party:'Lakeside Retail Co',category:'Client payment',method:'Check',check:'8821',amount:7200,memo:'Invoice #2465'},
      {id:'c11',date:'Jun 3',dir:'out',party:'Liberty Mutual',category:'Insurance',method:'ACH',check:'',amount:2100,memo:'Workers comp'},
      {id:'c12',date:'Jun 1',dir:'out',party:'Northbay Office LLC',category:'Rent',method:'Check',check:'1038',amount:4200,memo:'Carryover'},
    ],
    invoices:[
      {id:'iv1',client:'Cedar & Vine Hospitality',num:'2471',amount:7400,issued:'May 11',due:'Jun 10',status:'Overdue',age:38},
      {id:'iv2',client:'Summit Facilities',num:'2455',amount:5100,issued:'May 24',due:'Jun 23',status:'Overdue',age:21},
      {id:'iv3',client:'Apex Precision Mfg',num:'2490',amount:3200,issued:'Jun 14',due:'Jun 28',status:'Outstanding',age:4},
      {id:'iv4',client:'Riverside Dental Group',num:'2488',amount:2600,issued:'Jun 9',due:'Jul 9',status:'Outstanding',age:0},
      {id:'iv5',client:'Brightpath Home Health',num:'2480',amount:17500,issued:'May 30',due:'Jun 14',status:'Paid',age:0},
      {id:'iv6',client:'Harbor Point Clinics',num:'2470',amount:19000,issued:'May 26',due:'Jun 10',status:'Paid',age:0},
    ],
    payroll:[
      {id:'p1',name:'Marco Delgado',role:'Warehouse lead',hours:80,rate:28,type:'Hourly',since:'Mar 2024',email:'marco@hartline.com'},
      {id:'p2',name:'Tanya Reyes',role:'Floater',hours:64,rate:24,type:'Hourly',since:'Aug 2024',email:'tanya@hartline.com'},
      {id:'p3',name:'Dev Patel-Wynn',role:'Recruiter',salary:2400,type:'Salary',since:'Jan 2023',email:'dev@hartline.com'},
      {id:'p4',name:'Priya Shah',role:'Coordinator',salary:2100,type:'Salary',since:'Jun 2024',email:'priya@hartline.com'},
      {id:'p5',name:'Devon Wright',role:'Driver',hours:72,rate:26,type:'Hourly',since:'Oct 2024',email:'devon@hartline.com'},
    ],
    bills:[
      {id:'b1',vendor:'Northbay Office LLC',category:'Rent',amount:4200,dueDay:24,recurring:true,paid:false},
      {id:'b2',vendor:'Liberty Mutual',category:'Insurance',amount:2100,dueDay:22,recurring:true,paid:false},
      {id:'b3',vendor:'State tax deposit',category:'Taxes',amount:6300,dueDay:30,recurring:false,paid:false},
      {id:'b4',vendor:'QuickBooks + tools',category:'Software',amount:740,dueDay:12,recurring:true,paid:true},
      {id:'b5',vendor:'Fleet fuel card',category:'Vehicles',amount:1450,dueDay:26,recurring:true,paid:false},
    ],
    billForm:{vendor:'',category:'Rent',amount:'',dueDay:'',recurring:true}, addBill:false,
    compliance:[
      {id:'cp1',label:'Quarterly payroll taxes (941)',kind:'Tax',date:'Jun 30',daysOut:9,done:false},
      {id:'cp2',label:'Workers’ comp insurance renewal',kind:'Insurance',date:'Jul 1',daysOut:10,done:false},
      {id:'cp3',label:'Business license renewal',kind:'License',date:'Aug 5',daysOut:45,done:false},
      {id:'cp4',label:'Q3 estimated taxes',kind:'Tax',date:'Sep 15',daysOut:86,done:false},
    ],
    team:[
      {id:'t1',name:'Brandy Mangum',role:'Owner / CEO',dept:'Leadership',manager:'—',start:'Jan 2021',type:'Owner',comp:'Owner draw',monthlyCost:0,status:'active',email:'brandy@hartline.com',phone:'(206) 555-0100'},
      {id:'t2',name:'Dev Patel-Wynn',role:'Senior Recruiter',dept:'Recruiting',manager:'Brandy Mangum',start:'Jan 2023',type:'Salary',comp:'$58K/yr',monthlyCost:4830,status:'active',email:'dev@hartline.com',phone:'(206) 555-0121'},
      {id:'t3',name:'Renata Solis',role:'Client Success Manager',dept:'Client Success',manager:'Brandy Mangum',start:'Mar 2023',type:'Salary',comp:'$62K/yr',monthlyCost:5170,status:'active',email:'renata@hartline.com',phone:'(206) 555-0132'},
      {id:'t4',name:'Margo Quinn',role:'Client Success Manager',dept:'Client Success',manager:'Brandy Mangum',start:'Sep 2023',type:'Salary',comp:'$60K/yr',monthlyCost:5000,status:'active',email:'margo@hartline.com',phone:'(206) 555-0143'},
      {id:'t5',name:'Theo Banks',role:'Client Success Manager',dept:'Client Success',manager:'Brandy Mangum',start:'Feb 2024',type:'Salary',comp:'$59K/yr',monthlyCost:4920,status:'active',email:'theo@hartline.com',phone:'(206) 555-0154'},
      {id:'t6',name:'Priya Shah',role:'Staffing Coordinator',dept:'Operations',manager:'Brandy Mangum',start:'Jun 2024',type:'Salary',comp:'$50K/yr',monthlyCost:4170,status:'active',email:'priya@hartline.com',phone:'(206) 555-0165'},
      {id:'t7',name:'Marco Delgado',role:'Warehouse Lead',dept:'Field Ops',manager:'Priya Shah',start:'Mar 2024',type:'Hourly',comp:'$28/hr',monthlyCost:4480,status:'active',email:'marco@hartline.com',phone:'(206) 555-0176'},
      {id:'t8',name:'Tanya Reyes',role:'Floater',dept:'Field Ops',manager:'Priya Shah',start:'Aug 2024',type:'Hourly',comp:'$24/hr',monthlyCost:3070,status:'active',email:'tanya@hartline.com',phone:'(206) 555-0187'},
      {id:'t9',name:'Devon Wright',role:'Driver',dept:'Field Ops',manager:'Priya Shah',start:'Oct 2024',type:'Hourly',comp:'$26/hr',monthlyCost:3900,status:'active',email:'devon@hartline.com',phone:'(206) 555-0198'},
      {id:'t10',name:'Maya Lin',role:'Recruiter',dept:'Recruiting',manager:'Dev Patel-Wynn',start:'Jun 23, 2026',type:'Salary',comp:'$52K/yr',monthlyCost:4330,status:'onboarding',email:'maya@hartline.com',phone:'(206) 555-0210',
        onboarding:[{label:'Offer letter signed',done:true},{label:'I-9 & W-4 collected',done:true},{label:'Email + Slack provisioned',done:false},{label:'ATS / CRM access',done:false},{label:'Buddy assigned (James)',done:true},{label:'Week-1 plan shared',done:false}]},
    ],
    openRoles:[
      {id:'r1',title:'Senior Recruiter',dept:'Recruiting',openedDays:38,target:30,status:'Interviewing',hiringManager:'Dev Patel-Wynn',range:'$55–65K',type:'Full-time',
        jobPost:'Own full-cycle recruiting for healthcare & light-industrial clients. 3+ yrs agency staffing, ATS fluency, high-volume sourcing. Hybrid — Seattle.'},
      {id:'r2',title:'Client Success Manager',dept:'Client Success',openedDays:12,target:30,status:'Screening',hiringManager:'Brandy Mangum',range:'$60–70K',type:'Full-time',
        jobPost:'Carry a book of 25–30 staffing accounts. Drive renewals, health, and expansion. 2+ yrs CSM or account management in services. Remote-friendly.'},
      {id:'r3',title:'Staffing Coordinator',dept:'Operations',openedDays:5,target:30,status:'Sourcing',hiringManager:'Priya Shah',range:'$45–52K',type:'Full-time',
        jobPost:'Schedule shifts, manage floaters, keep coverage tight. Detail-obsessed, calm under pressure, great on the phone. On-site — Seattle warehouse.'},
    ],
    candidates:{
      r1:[
        {id:'c1',name:'Jordan Lee',stage:'offer',applied:'May 28',rating:5,daysWaiting:4,note:'Strong — 5 yrs agency, healthcare focus. Offer drafted, ready to send.',history:[{label:'Applied via inbound',time:'May 28 · 9:12 AM'},{label:'Phone screen — strong',time:'Jun 2 · 11:00 AM'},{label:'Moved to Interview',time:'Jun 6 · 2:30 PM'},{label:'Final interview — great',time:'Jun 9 · 10:00 AM'},{label:'Rated 5★',time:'Jun 9 · 10:45 AM'},{label:'Moved to Offer · offer drafted',time:'Jun 17 · 4:20 PM'}]},
        {id:'c2',name:'Sam Rivera',stage:'interview',applied:'Jun 2',rating:4,daysWaiting:5,note:'Great phone screen. Final interview done — awaiting your thumbs up.',history:[{label:'Applied via referral',time:'Jun 2 · 1:05 PM'},{label:'Phone screen — strong',time:'Jun 6 · 3:15 PM'},{label:'Moved to Interview',time:'Jun 11 · 9:30 AM'},{label:'Rated 4★',time:'Jun 16 · 5:00 PM'}]},
        {id:'c3',name:'Alex Kim',stage:'screen',applied:'Jun 10',rating:3,daysWaiting:1,note:'Solid resume, lighter on healthcare. Phone screen scheduled.',history:[{label:'Applied via LinkedIn',time:'Jun 10 · 8:40 AM'},{label:'Moved to Screen',time:'Jun 19 · 10:10 AM'},{label:'Rated 3★',time:'Jun 19 · 10:12 AM'}]},
        {id:'c4',name:'Dana Cruz',stage:'applied',applied:'Jun 18',rating:0,daysWaiting:0,note:'New inbound — not yet reviewed.',history:[{label:'Applied via inbound',time:'Jun 18 · 7:22 PM'}]},
        {id:'c5',name:'Pat Nolan',stage:'applied',applied:'Jun 19',rating:0,daysWaiting:0,note:'New inbound — not yet reviewed.',history:[{label:'Applied via inbound',time:'Jun 19 · 8:01 AM'}]},
      ],
      r2:[
        {id:'c6',name:'Maria Gomez',stage:'interview',applied:'Jun 8',rating:4,daysWaiting:2,note:'Came from a competitor agency. Strong renewal track record.',history:[{label:'Applied via inbound',time:'Jun 8 · 12:30 PM'},{label:'Phone screen — strong',time:'Jun 11 · 2:00 PM'},{label:'Moved to Interview',time:'Jun 18 · 11:15 AM'},{label:'Rated 4★',time:'Jun 18 · 11:50 AM'}]},
        {id:'c7',name:'Chris Park',stage:'screen',applied:'Jun 12',rating:3,daysWaiting:1,note:'SaaS CSM background, transferable. Screening this week.',history:[{label:'Applied via LinkedIn',time:'Jun 12 · 4:45 PM'},{label:'Moved to Screen',time:'Jun 19 · 9:00 AM'},{label:'Rated 3★',time:'Jun 19 · 9:05 AM'}]},
        {id:'c8',name:'Tasha Bell',stage:'applied',applied:'Jun 17',rating:0,daysWaiting:0,note:'Referred by Margo.',history:[{label:'Applied via referral (Margo)',time:'Jun 17 · 3:20 PM'}]},
      ],
      r3:[
        {id:'c9',name:'Leo Mendez',stage:'applied',applied:'Jun 18',rating:0,daysWaiting:0,note:'Dispatch background — promising.',history:[{label:'Applied via inbound',time:'Jun 18 · 10:05 AM'}]},
        {id:'c10',name:'Robin Tate',stage:'applied',applied:'Jun 20',rating:0,daysWaiting:0,note:'New inbound.',history:[{label:'Applied via inbound',time:'Jun 20 · 1:40 PM'}]},
      ],
    },
    hiringTab:'roster', openTeamId:null, expandedRole:null,
    empForm:{name:'',role:'',type:'Hourly',rate:'',salary:'',email:''}, addEmp:false, openEmpId:null,
    addTeam:false, teamForm:{name:'',role:'',dept:'Recruiting',manager:'Brandy Mangum',type:'Salary',comp:'',email:'',phone:'',start:''},
    addRole:false, roleForm:{title:'',dept:'Recruiting',range:'',hiringManager:'Brandy Mangum',type:'Full-time',jobPost:''},
    addCand:false, candRoleId:null, candForm:{name:'',note:''},
    templateCats:['Collections','Renewals','Re-engagement','Prospect outreach'],
    openTplId:null, tplEditId:null, tplEditForm:null,
    templates:[
      {id:'tplcol1',cat:'Collections',audience:'Customer',name:'Payment due — friendly',step:'1st',subject:'Quick note on invoice {{invoice}}',body:"Hi {{contact}},\n\nJust a friendly heads-up that invoice {{invoice}} for {{amount}} is due {{date}}. If it's already on the way, thank you — please disregard.\n\nAnything you need from us to get it processed? Happy to help.\n\nBest,\nBrandy"},
      {id:'tplcol2',cat:'Collections',audience:'Customer',name:'Second reminder',step:'2nd',subject:'Following up — invoice {{invoice}}',body:"Hi {{contact}},\n\nCircling back on invoice {{invoice}} for {{amount}}, now a few days past due — I wanted to make sure it didn't slip through the cracks.\n\nCould you let me know the expected payment date? If there's a hold-up on your end, I'm glad to help sort it out.\n\nThanks,\nBrandy"},
      {id:'tplcol3',cat:'Collections',audience:'Customer',name:'Final notice',step:'3rd',subject:'Action needed — invoice {{invoice}} overdue',body:"Hi {{contact}},\n\nInvoice {{invoice}} for {{amount}} is now significantly overdue and I haven't been able to reach you. To keep your account in good standing and avoid any pause in coverage, we'll need payment by {{date}}.\n\nIf there's an issue, please call me directly today and we'll work it out.\n\nRegards,\nBrandy"},
      {id:'tplmonthly',cat:'Collections',audience:'Customer',name:'Monthly collection',step:'—',subject:'{{company}} — {{month}} invoice',body:"Hi {{contact}},\n\nYour {{month}} invoice ({{amount}}) is ready and due {{date}}. Same as always — just flag me if anything looks off.\n\nThanks for the continued partnership,\nBrandy"},
      {id:'tplrenew',cat:'Renewals',audience:'Customer',name:'Renewal coming up',step:'—',subject:"Let's talk about your renewal",body:"Hi {{contact}},\n\nYour agreement with us is up for renewal on {{date}}, and I'd love 20 minutes to talk about what's working, what we can do better, and the year ahead.\n\nDo you have time this week or next? I'll send a couple of options.\n\nBest,\nBrandy"},
      {id:'tplreengage',cat:'Re-engagement',audience:'Customer',name:"Haven't heard from you",step:'—',subject:'Checking in, {{contact}}',body:"Hi {{contact}},\n\nIt's been a little while since we connected and I want to make sure {{company}} is getting everything you need from us. Sometimes quiet means all-good, sometimes it means something slipped — either way, I'd rather ask.\n\nHow are things going on your end? A quick reply means a lot.\n\nWarmly,\nBrandy"},
      {id:'tplout1',cat:'Prospect outreach',audience:'Prospect',name:'Intro / first touch',step:'1st',subject:'Helping {{company}} stay covered',body:"Hi {{contact}},\n\nI help teams like {{company}} stay fully staffed without the scramble — covering the roles that are hardest to fill and quickest to hurt when they sit open.\n\nWorth a short conversation to see if we're a fit? I'll keep it to 15 minutes.\n\nBest,\nBrandy"},
      {id:'tplout2',cat:'Prospect outreach',audience:'Prospect',name:'Follow-up',step:'2nd',subject:'Following up, {{contact}}',body:"Hi {{contact}},\n\nWanted to float my note from last week back to the top of your inbox. No worries if the timing's off — I know things get busy.\n\nIf staffing coverage is on your mind at all this quarter, I'd love to compare notes. When's good?\n\nThanks,\nBrandy"},
      {id:'tplout3',cat:'Prospect outreach',audience:'Prospect',name:'Last attempt',step:'3rd',subject:'Should I close the loop?',body:"Hi {{contact}},\n\nI've reached out a couple of times and haven't heard back, so I'll assume the timing isn't right and stop here for now.\n\nIf that changes — a tough role to fill, a coverage gap, a busy season coming — just reply and I'll jump on it.\n\nAll the best,\nBrandy"},
    ],
    feed:[
      {id:'f1',text:'Flagged Northwind Logistics — health fell 18 pts in 9 days',time:'2h ago',kind:'alert'},
      {id:'f2',text:'Drafted a re-engagement email for Cedar & Vine',time:'3h ago',kind:'draft'},
      {id:'f3',text:'Matched 6 payments to invoices in QuickBooks',time:'5h ago',kind:'sync'},
      {id:'f4',text:'Synced 12 new placements from your Google Sheet',time:'Yesterday',kind:'sync'},
    ],
};

window.CHA_EXTRAS = {
    a1:{csm:'Theo',segment:'Mid-Market',renewal:'Jan 2027',tickets:3,platform:'OEM',started:'Mar 2024',term:'12-mo · auto-renew'},
    a2:{csm:'Brandy',segment:'Scaled',renewal:'Jul 2027',tickets:1,platform:'API',started:'Jun 2024',term:'Month-to-month'},
    a3:{csm:'Brandy',segment:'Enterprise',renewal:'Jul 2026',tickets:5,platform:'OEM',started:'Aug 2023',term:'24-mo'},
    a4:{csm:'Renata',segment:'Mid-Market',renewal:'Jan 2027',tickets:2,platform:'API',started:'Jan 2025',term:'12-mo'},
    a5:{csm:'Brandy',segment:'Scaled',renewal:'Nov 2026',tickets:0,platform:'OEM',started:'Nov 2024',term:'12-mo · auto-renew'},
    a6:{csm:'Brandy',segment:'Scaled',renewal:'Mar 2028',tickets:0,platform:'API',started:'Feb 2025',term:'12-mo'},
    a7:{csm:'Margo',segment:'Mid-Market',renewal:'May 2027',tickets:1,platform:'OEM',started:'Oct 2023',term:'24-mo'},
    a8:{csm:'Brandy',segment:'Enterprise',renewal:'May 2027',tickets:1,platform:'OEM',started:'Jul 2023',term:'24-mo · auto-renew'},
};
